pipeline:
  - PT
  - IFT
  - RFT
  - TC
    
dataset:
  PT:
    - base: "HuggingFaceFW/fineweb-edu"
      subset: "sample-10BT"
      split: train
      limit: 100 # 1000
      learning_rate: 3e-4
      text_column: text
    
    # - base: "HuggingFaceFW/fineweb"
    #   subset: "sample-10BT"
    #   split: train
    #   limit: 100 # 1000
    #   learning_rate: 3e-4
    #   text_column: text
    
    - base: "bigcode/the-stack"
      data_dir: "data/json"
      split: train
      limit: 10971
      text_column: content
    
    - base: "bigcode/the-stack"
      data_dir: "data/shell"
      split: train
      limit: 98756
      text_column: content
    
    # - base: "HuggingFaceTB/smollm-corpus"
    #   subset: "cosmopedia-v2"
    #   split: train
    #   limit: 100
    #   text_column: text
    
    # - base: "bigcode/the-stack"
    #   data_dir: "data/api-blueprint"
    #   split: train
    #   limit: 3312
    #   text_column: content
    
    # - base: "bigcode/the-stack"
    #   data_dir: "data/python"
    #   split: train
    #   limit: 26276
    #   text_column: content
    
    # - base: "bigcode/the-stack"
    #   data_dir: "data/markdown"
    #   split: train
    #   limit: 26276
    #   text_column: content
    
    # - base: "emozilla/pg19"
    #   subset: NULL
    #   split: train
    #   limit: 100
    #   text_column: text
    
    # - base: "HuggingFaceFW/fineweb"
    #   subset: "sample-10BT"
    #   split: train
    #   limit: 100
    #   text_column: text
  
  IFT:
    - base: "HuggingFaceH4/ultrachat_200k"
      subset: NULL
      split: train_sft
      limit:  NULL
      learning_rate: 1e-4
    
  RFT:
    - base: "Scale-or-Reason/general-reasoning-ift-pairs"
      subset: NULL
      split: reasoning_ift_pairs
      limit: 330000
      max_seq_len: 1024
      batch_size: 4
      grad_accum_steps: 16
      learning_rate: 1e-5
  
  TC:
    - base: "korotkov/glaive-function-calling-v2-parsed"
      subset: NULL
      split: train
      limit: NULL
      max_seq_len: 2048
      batch_size: 1
      grad_accum_steps: 16
      learning_rate: 1e-5